version: "3.7"

services:
    database_ignite:
        image: postgres
        container_name: database_ignite
        restart: always
        ports: 
            - 65432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=rentalx
        volumes: 
            - pgdata:/data/postgres 

volumes:
    pgdata:
        driver: local